### ISSUE TITLE
Input preprocessing

### ISSUE THREAD

**Issue by HimaVarsha94** [chantera/biaffineparser#1]
Can you tell more about the format in which input has to be given? It has not been mentioned in the Readme and I am having an issue using this repo.

**Comment by chantera** [comment]
Sorry for the late reply.
Input files must be written in CoNLL-X format: http://anthology.aclweb.org/W/W06/W06-2920.pdf
Words are lowercased and numbers replaced with the character '0' in preprocessing: 
https://github.com/chantera/biaffineparser/blob/e59135334b1cbf5bbe6997da51ca8dd797da6f49/utils.py#L193
